name: Build Workflow
on:
  workflow_call:
    inputs:
      stage:
        required: false
        type: string
      resource:  
        required: false
        type: string
      java-version:
        required: false
        type: string
        default: '11'
      maven-params:
        required: false
        type: string
        default: ''
jobs:
  build-artifact:
    name: Build artifact for ${{ inputs.resource }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
     
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.resource }} 

    steps:
     - name: Checkout code for ${{ inputs.resource }} 
       uses: actions/checkout@v4
     - uses: graalvm/setup-graalvm@v1
       with:
          java-version: '17'      # See 'Options' section below for all supported versions
          distribution: 'graalvm-community' # See 'Options' section below for all available distributions
          github-token: ${{ secrets.GITHUB_TOKEN }}
     - name: Example step
       run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
     - name: Example step using Maven plugin  # https://graalvm.github.io/native-build-tools/latest/maven-plugin.html
       run: mvn -Pnative package
  lint-codebase:
    name: Lint Code Base for ${{ inputs.resource }}
    runs-on: ubuntu-latest
    needs: build-artifact
    permissions:
      contents: read  
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.resource }} 
    steps:
     - name: Checkout Code for ${{ inputs.resource }} 
       uses: actions/checkout@v4
       with:
         fetch-depth: 0
     - name: Linting folder ${{ inputs.resource }} 
       uses: github/super-linter/slim@v4
       env:
         FILTER_REGEX_INCLUDE: .*src/.*
         FILTER_REGEX_EXCLUDE: .*test/.*
         VALIDATE_ALL_CODEBASE: false
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         VALIDATE_JAVA: true
         DISABLE_ERRORS: true
         
           
